2019-03-11 11:24:07,475_MainThread_[ERROR] : 这是debug
2019-03-11 11:24:07,475_MainThread_[ERROR] : 这是debug
2019-03-11 11:24:07,475_MainThread_[ERROR] : failed : 
Traceback (most recent call last):
  File "F:/share/selenium/aiostore/aiotest2019/common/logpy.py", line 70, in <module>
    f = open('ff','r')
FileNotFoundError: [Errno 2] No such file or directory: 'ff'
2019-03-11 11:24:07,475_MainThread_[ERROR] : failed : 
Traceback (most recent call last):
  File "F:/share/selenium/aiostore/aiotest2019/common/logpy.py", line 70, in <module>
    f = open('ff','r')
FileNotFoundError: [Errno 2] No such file or directory: 'ff'
2019-03-11 11:32:32,549_MainThread_[ERROR] : 这是debug
2019-03-11 11:32:32,550_MainThread_[ERROR] : failed : 
Traceback (most recent call last):
  File "F:/share/selenium/aiostore/aiotest2019/common/logpy.py", line 71, in <module>
    f = open('ff','r')
FileNotFoundError: [Errno 2] No such file or directory: 'ff'
2019-03-11 11:33:01,452_MainThread_[INFO] : admin admin1 False
2019-03-11 11:33:01,465_MainThread_[INFO] : admin admin2 False
2019-03-11 11:33:01,478_MainThread_[INFO] : xx xx True
2019-03-11 11:33:01,485_MainThread_[INFO] : admin admin True
2019-03-11 11:33:36,914_MainThread_[INFO] : admin admin1 False
2019-03-11 11:33:36,928_MainThread_[INFO] : admin admin2 False
2019-03-11 11:33:36,936_MainThread_[INFO] : xx xx True
2019-03-11 11:33:36,944_MainThread_[INFO] : admin admin True
